name: SchematicsExtended
version: @version@
main: net.islandearth.schematics.extended.example.SchematicPlugin
api-version: 1.17
load: STARTUP
authors: [SamB440, brainsynder, Math0424]
description: Build schematics block-by-block!
website: https://gitlab.com/SamB440/Schematics-Extended
